use_frameworks!

platform :ios, '8.0'

target 'TLCrash_Example' do
  pod 'TLCrash', :path => '../'

  target 'TLCrash_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
